name: 798x
on:
  workflow_dispatch:
    inputs:
      subnet:
        description: "默认IP地址:192.168.[].1"
        required: true
        default: "5"
  schedule:
    - cron: '0 22 * * 5'  # 每周五 UTC 22:00，即每周六中国时间 6:00

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6.git  
  REPO_BRANCH: openwrt-24.10-6.6
  CONFIG_FILE: mt798x/2410.config
  CUSTOM_SCRIPT: mt798x/custom.sh
  CLASH_KERNEL: arm64
  CACHE_TOOLCHAIN: true
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: mt798x
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:

    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(nproc --all | grep -c '^')"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo)\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息: $(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Free disk space
      uses: sbwml/actions@free-disk

    - name: Build System Setup
      run: |
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E apt -yqq install dos2unix rename
        sudo -E apt -yqq install libfuse-dev
        sudo -E apt -yqq autoremove --purge
        sudo -E apt -yqq autoclean
        sudo -E apt -yqq clean
        sudo -E systemctl daemon-reload

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone Source Code
      run: |
        git clone --depth=1 -b $REPO_BRANCH $REPO_URL openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV

    - name: Generate Variables
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          SUBNET="${{ github.event.inputs.subnet }}"
          [ -z "$SUBNET" ] && SUBNET="5"
        else
          SUBNET="5"
        fi
        echo "SUBNET=$SUBNET" >> $GITHUB_ENV
          
        # 提取源码仓库名（例如 AutoBuild-OpenWrt）
        echo "SOURCE_REPO=$(echo $REPO_URL | awk -F '/' '{print $(NF)}')" >> $GITHUB_ENV

        # 提取设备主架构（例如 x86、qualcommax）
        echo "DEVICE_TARGET=$(grep CONFIG_TARGET_BOARD .config | awk -F '\"' '{print $2}')" >> $GITHUB_ENV

        # 提取设备子架构（例如 64、ipq60xx）
        echo "DEVICE_SUBTARGET=$(grep CONFIG_TARGET_SUBTARGET .config | awk -F '\"' '{print $2}')" >> $GITHUB_ENV

        # 提取架构包名（例如 x86_64、aarch64_cortex-a53）
        echo "DEVICE_ARCH=$(sed -n 's/^CONFIG_TARGET_ARCH_PACKAGES="\([^"]*\)"/\1/p' .config)" >> $GITHUB_ENV

        # 提取设备型号（例如 generic、zn_m2）
        echo "DEVICE_MODEL=$(sed -n 's/^CONFIG_TARGET_PROFILE="DEVICE_\([^"]*\)"/\1/p' .config)" >> $GITHUB_ENV
        
        # 写入缓存时间（20250813-只保留当天）
        echo "CACHE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
    - name: 缓存工具链
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: actions/cache@v4
      id: cache-toolchain
      with:
        key: ${{ env.REPO_URL }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.CACHE_DATE }}
        restore-keys: |
          ${{ env.REPO_URL }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-
        path: |
          ${{ env.OPENWRT_PATH }}/.ccache
          ${{ env.OPENWRT_PATH }}/staging_dir

    - name: 输出缓存结果
      run: |
        echo "使用的缓存键: ${{ steps.cache-toolchain.outputs.cache-key }}"
        echo "缓存命中情况: ${{ steps.cache-toolchain.outputs.cache-hit }}"
        echo "缓存目录大小："
        du -sh ${{ env.OPENWRT_PATH }}/.ccache || echo ".ccache 目录不存在"
        du -sh ${{ env.OPENWRT_PATH }}/staging_dir || echo "staging_dir 目录不存在"

    - name: 刷新缓存时间戳
      run: |
        echo "开始刷新缓存时间戳..."
        if [ -d "$OPENWRT_PATH/staging_dir" ]; then
          find "$OPENWRT_PATH/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r dir; do
            find "$dir" -type f -exec touch {} +
          done
        fi
        echo "缓存时间戳刷新完成。"

    - name: 添加定时触发的值
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          SUBNET="${{ github.event.inputs.subnet }}"
          [ -z "$SUBNET" ] && SUBNET="5"
        else
          SUBNET="5"
        fi
        echo "SUBNET=$SUBNET" >> $GITHUB_ENV

    - name: Install Feeds
      run: |
        cd $OPENWRT_PATH
        ./scripts/feeds update -a               
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      env:
        SUBNET: ${{ env.SUBNET }}
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $OPENWRT_PATH/.config
        chmod +x $GITHUB_WORKSPACE/scripts/*.sh $CUSTOM_SCRIPT
        cd $OPENWRT_PATH/package/
        $GITHUB_WORKSPACE/scripts/Packages.sh
        $GITHUB_WORKSPACE/scripts/Handles.sh
        $GITHUB_WORKSPACE/$CUSTOM_SCRIPT
        $GITHUB_WORKSPACE/scripts/patch-tailscale.sh        

    - name: Download DL Package
      run: |
        cd $OPENWRT_PATH
        
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile Firmware
      id: compile
      run: |
        cd $OPENWRT_PATH
        mkdir -p files/etc/uci-defaults
        cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
        cp $GITHUB_WORKSPACE/scripts/init-tailscale.sh files/etc/uci-defaults/99-init-tailscale
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Check Space Usage
      if: (!cancelled())
      run: df -hT

    - name: Upload Bin Directory
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.REPO_URL }}-bin-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        path: ${{ env.OPENWRT_PATH }}/bin

    - name: Prepare artifact
      run: |
        cd $OPENWRT_PATH
        mkdir -p ./artifact/package ./artifact/buildinfo
        cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
        cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

    - name: Upload buildinfo
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_buildinfo
        path: ${{ env.OPENWRT_PATH }}/artifact/buildinfo/

    - name: Upload package
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_package
        path: ${{ env.OPENWRT_PATH }}/artifact/package/

    - name: Organize Files
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        echo "KERNEL=$(grep '^kernel' *.manifest | sed -n 's/^kernel - \([0-9.]*\)~.*/\1/p')" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
        $GITHUB_WORKSPACE/scripts/cleanup_targets.sh
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Upload Firmware To Release
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: ncipollo/release-action@main
      with:
        name: R${{ env.DATE }} for ${{ env.DEVICE_TARGET }}
        allowUpdates: true
        tag: ${{ env.DEVICE_TARGET }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          ### 📋 固件信息
          -  🔧 平台架构: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
          -  📦 固件源码: ${{ env.REPO_URL }}
          -  🌿 源码分支: ${{ env.REPO_BRANCH }}
          -  ⚙️ 内核版本: ${{ env.KERNEL }}        

    - name: Send Telegram Message
      run: |
        CURRENT_DATE_TIME=$(TZ='Asia/Shanghai' date +'%Y/%m/%d %r')
        MESSAGE="${{ env.DEVICE_MODEL }} 固件编译完成
        发布时间：$CURRENT_DATE_TIME
        发布页面：https://github.com/acnixuil/AutoBuild_OP/releases/tag/${{ env.DEVICE_TARGET }}"
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="$MESSAGE"

    - name: 删除旧缓存
      run: |
        echo "开始列出并删除旧缓存..."
        gh cache list --key ${{ env.REPO_URL }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}- --json key --jq '.[] | .key' | while read -r key; do
          echo "删除缓存：$key"
          gh cache delete "$key"
        done
        echo "当前缓存使用情况："
        echo "ccache 目录大小: $(du -sh ${{ env.OPENWRT_PATH }}/.ccache | cut -f 1)"
        echo "staging_dir 目录大小: $(du -sh ${{ env.OPENWRT_PATH }}/staging_dir | cut -f 1)"