#===============================================
# Description: ARMv8 OpenWrt
# Lisence: MIT
# By：Jejz
#===============================================

name: ARMv8 OpenWrt快速打包

on:
  workflow_dispatch:
  #schedule:
    #- cron: '45 22 * * *'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ./n1/p/p_n1.config
  DIY_P1_SH: ./n1/p/p_n1_part1.sh
  DIY_P2_SH: ./n1/p/p_n1_part2.sh
  UPLOAD_RELEASE: true
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TZ: Asia/Shanghai
  FILE_NAME: armv8
  PRODUCT_NAME: armv8

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/compile-kernel/tools/script/ubuntu2204-make-openwrt-depends)
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
          
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        Author=$(git show -s --date=short --format="Author: %an")
        Date=$(git show -s --date=short --format="date: %ci")
        Commit=$(git show -s --date=short --format="commit: %s")
        Hash=$(git show -s --date=short --format="commit hash: %h")
        echo "author=$Author" >> $GITHUB_ENV
        echo "date=$Date" >> $GITHUB_ENV
        echo "commit=$Commit" >> $GITHUB_ENV
        echo "hash=$Hash" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "TAG=$(date "+%Y%m%d")" >> $GITHUB_ENV
        echo "TAG=$(date "+%Y%m%d")" >> $GITHUB_ENV
        echo "start=$(date +%s)" >> $GITHUB_ENV
    
    - name: 打包固件
      uses: acnixuil/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: https://github.com/acnixuil/AutoBuild_OP/releases/download/armv8/openwrt-armvirt-64-generic-rootfs.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_AUTO_LATEST: true
        KERNEL_VERSION_NAME: 6.1.1
        ENABLE_WIFI_K504: 0
        ENABLE_WIFI_K510: 0
        WHOAMI: EnjoyToday
        KERNEL_REPO_URL: breakings/OpenWrt
        SCRIPT_REPO_URL: acnixuil/openwrt_packit
        SCRIPT_REPO_BRANCH: master

    - name: 上传到Release
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} 「 ${{ env.FILE_NAME }} 」固件
        allowUpdates: true
        tag: ${{ env.TAG }}_${{ env.PRODUCT_NAME }}_p
        token: ${{ secrets.G_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH  }}/*
