name: Test Workflow

on:
  push:
    branches:
      - main
env:
  FIRMWARE_TAG: X86_64
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display Variables
      run: |
        echo "GitHub Event Name: $GITHUB_EVENT_NAME"
        echo "GitHub Event Path: $GITHUB_EVENT_PATH"
        echo "GitHub Workspace: $GITHUB_WORKSPACE"
        echo "GitHub SHA: $GITHUB_SHA"
        echo "GitHub Ref: $GITHUB_REF"
        echo "GitHub Actor: $GITHUB_ACTOR"
        echo "GitHub Repository: $GITHUB_REPOSITORY"
        echo "GitHub Run ID: $GITHUB_RUN_ID"
        echo "GitHub Run Number: $GITHUB_RUN_NUMBER"
        echo "GitHub Event Created At: $GITHUB_EVENT_CREATED_AT"
        echo "GitHub Run At: $GITHUB_RUN_AT"
        echo "FIRMWARE_TAG: $FIRMWARE_TAG"
        echo "TELEGRAM_TOKEN: $TELEGRAM_TOKEN"
        echo "TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID"
        echo "ACTION_WORKFLOW: $GITHUB_WORKFLOW"
        echo "ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
        echo "ACTION_REF: $GITHUB_ACTION_REF"
        echo "ACTION: $GITHUB_ACTION"
        echo "HEAD_REF: $GITHUB_HEAD_REF"
        echo "BASE_REF: $GITHUB_BASE_REF"
        echo "EVENT_PATH: $GITHUB_EVENT_PATH"
        echo "EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "EVENT_PATH: $GITHUB_EVENT_PATH"
        echo "EVENT_ACTOR: $GITHUB_EVENT_ACTOR"
        echo "EVENT_BEFORE: $GITHUB_EVENT_BEFORE"
        echo "EVENT_AFTER: $GITHUB_EVENT_AFTER"
        echo "EVENT_HEAD: $GITHUB_EVENT_HEAD"
        echo "EVENT_BASE: $GITHUB_EVENT_BASE"
        echo "EVENT_CREATED_AT: $GITHUB_EVENT_CREATED_AT"
        echo "EVENT_UPDATED_AT: $GITHUB_EVENT_UPDATED_AT"
        echo "RUNNER_OS: $RUNNER_OS"
        echo "RUNNER_TEMP: $RUNNER_TEMP"
        echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
        echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
        
    - name: Send Telegram Message
      run: |
        # 获取当前北京时间
        CURRENT_DATE_TIME=$(TZ='Asia/Shanghai' date +'%Y/%m/%d %r')

        # 计算 GitHub Action 运行时间
        START_TIME=$(date -u -d "${{ github.event.created_at }}" '+%s')
        END_TIME=$(date -u -d "${{ github.run_at }}" '+%s')
        DURATION_SECONDS=$((END_TIME - START_TIME))
        DURATION_HOURS=$((DURATION_SECONDS / 3600))
        DURATION_MINUTES=$((DURATION_SECONDS % 3600 / 60))
            
        # 格式化运行时间为 HH:MM
        DURATION_FORMATTED="$(printf "%02d:%02d" $DURATION_HOURS $DURATION_MINUTES)"

        # 构建消息
        MESSAGE="${{ env.FIRMWARE_TAG }} 固件编译完成
        耗时：$DURATION_FORMATTED
        信息发送时间：$CURRENT_DATE_TIME
        发布页面：https://github.com/acnixuil/AutoBuild_OP/releases/tag/${{ env.FIRMWARE_TAG }}"

        # 发送消息到 Telegram
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="$MESSAGE"